version: '3.8'

services:
  mysql-service:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - net-wp
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 30s

  wordpress-service:
    image: wordpress:6
    container_name: wordpress-container
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql-container
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - wordpress-vol:/var/www/html
    networks:
      - net-wp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 50s
    restart: always

volumes:
  mysql-data:
  wordpress-vol:

networks:
  net-wp:
    driver: bridge
